# This is a basic workflow to help you get started with Actions

name: Template Repository Initialization

# Controls when the workflow will run
on:
  # Triggers the workflow on creation of repository
  create:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Replaces the template repository name in the README with the new one
      - name: Update README
        run: |
          sed -i "s|GITHUB_REPOSITORY_OWNER|${{ github.repository_owner }}|g" template_README.md
          sed -i "s|GITHUB_REPOSITORY|${{ github.repository }}|g" template_README.md
          mv template_README.md README.md

      # Deletes this workflow file to prevent it from running on branch creation
      - name: Delete initialization workflow
        run: rm .github/workflows/initialize.yml

      # Commits all changes
      - name: Commit repository initialization
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com
          git commit -am "Repository initialization"
          git push
